### ISSUE TITLE
求教大佬如何运行爬虫

### ISSUE THREAD

**Issue by Huberyky** [tianranchunzhen/ZhihuTopicCrawler#1]
请问作者大大如何运行爬虫，我是刚刚开始入门爬虫的社科萌新，看到作者的项目很有趣，想向大佬请教一下

**Comment by Yousa-Mirage** [comment]
在运行前，首先需要更新`get_url_text.py`里的cookie。先在网页知乎登录账号，打开浏览器开发者工具(F12)切换到 Network 窗口，从里面找到请求头里的cookie，复制到`get_url_text.py`里。
可以先运行`scraping1.py`试试，只需要在TODO标记处填写想要爬取的知乎话题ID`topicID_list`，运行Python脚本就行了。

**Comment by Huberyky** [comment]
学会了，多谢指教~

**Comment by Yousa-Mirage** [comment]
不客气，祝学习顺利~
